# -*- cmake -*-


MACRO(ADD_BUILD_TEST_NO_COMMON name parent)

ENDMACRO(ADD_BUILD_TEST_NO_COMMON name parent)


MACRO(ADD_BUILD_TEST name parent)

ENDMACRO(ADD_BUILD_TEST name parent)


MACRO(ADD_VIEWER_BUILD_TEST name parent)

ENDMACRO(ADD_VIEWER_BUILD_TEST name parent)


MACRO(ADD_SIMULATOR_BUILD_TEST name parent)

ENDMACRO(ADD_SIMULATOR_BUILD_TEST name parent)

MACRO(ADD_BUILD_TEST_INTERNAL name parent libraries source_files)

ENDMACRO(ADD_BUILD_TEST_INTERNAL name parent libraries source_files)


MACRO(ADD_COMM_BUILD_TEST name parent wrapper)

ENDMACRO(ADD_COMM_BUILD_TEST name parent wrapper)

MACRO(ADD_VIEWER_COMM_BUILD_TEST name parent wrapper)

ENDMACRO(ADD_VIEWER_COMM_BUILD_TEST name parent wrapper)

MACRO(SET_TEST_PATH LISTVAR)

ENDMACRO(SET_TEST_PATH)
